apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-eks
spec:
  replicas: 3
  selector:
    matchLabels:
      app: springboot-eks
  template:
    metadata:
      labels:
        app: springboot-eks
    spec:
      containers:
        - name: springboot-eks
          image: 069631898237.dkr.ecr.us-east-1.amazonaws.com/springboot-eks:latest
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: springboot-eks-service
spec:
  selector:
    app: springboot-eks
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer